In [1]:
import requests
import torch
from PIL import Image
from transformers import AutoProcessor, AutoModelForZeroShotObjectDetection, pipeline
from pathlib import Path
import glob
import os
from transformers import CLIPProcessor, CLIPModel

In [ ]:
device = "cuda" if torch.cuda.is_available() else "cpu"

dino_id = "IDEA-Research/grounding-dino-tiny"
dino_processor = AutoProcessor.from_pretrained(dino_id)
dino = AutoModelForZeroShotObjectDetection.from_pretrained(dino_id).to(device)

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:112: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(
Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

preprocessor_config.json:   0%|          | 0.00/457 [00:00<?, ?B/s]

The image processor of type `GroundingDinoImageProcessor` is now loaded as a fast processor by default, even if the model checkpoint was saved with a slow processor. This is a breaking change and may produce slightly different outputs. To continue using the slow processor, instantiate this class with `use_fast=False`.

config.json:   0%|          | 0.00/1.64k [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/1.24k [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/711k [00:00<?, ?B/s]

added_tokens.json:   0%|          | 0.00/82.0 [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/125 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/689M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/990 [00:00<?, ?it/s]

In [ ]:
clip = CLIPModel.from_pretrained("openai/clip-vit-base-patch32", torch_dtype=torch.float16)
clip_processor = CLIPProcessor.from_pretrained("openai/clip-vit-base-patch32")

config.json:   0%|          | 0.00/4.19k [00:00<?, ?B/s]

pytorch_model.bin:   0%|          | 0.00/605M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/398 [00:00<?, ?it/s]

model.safetensors:   0%|          | 0.00/605M [00:00<?, ?B/s]

CLIPModel LOAD REPORT from: openai/clip-vit-base-patch32
Key                                  | Status     |  |
-------------------------------------+------------+--+-
text_model.embeddings.position_ids   | UNEXPECTED |  |
vision_model.embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

preprocessor_config.json:   0%|          | 0.00/316 [00:00<?, ?B/s]

The image processor of type `CLIPImageProcessor` is now loaded as a fast processor by default, even if the model checkpoint was saved with a slow processor. This is a breaking change and may produce slightly different outputs. To continue using the slow processor, instantiate this class with `use_fast=False`.

tokenizer_config.json:   0%|          | 0.00/592 [00:00<?, ?B/s]

vocab.json:   0%|          | 0.00/862k [00:00<?, ?B/s]

merges.txt:   0%|          | 0.00/525k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/2.22M [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/389 [00:00<?, ?B/s]

In [ ]:
# Carga de datos
# Esta celda descarga todos los datos, y los extrae

url = 'https://drive.google.com/drive/folders/1MvRYh3SudRabydH2eAAzRq2K5Os1j41-'
output_folder = 'recsys-pf'

gdown.download_folder(url, output=output_folder, quiet=False, use_cookies=False)
zip_search_pattern = os.path.join(output_folder, '*.zip')
zip_files = glob.glob(zip_search_pattern)
image_zip_path = zip_files[0]

with zipfile.ZipFile(image_zip_path, 'r') as zip_ref:
    zip_ref.extractall(output_folder)

In [4]:
import pandas as pd
import numpy as np

interaction_df = pd.read_csv('recsys-pf/interaction.csv')
item_info_df = pd.read_csv('recsys-pf/item_info.csv')

In [13]:
semilla = 5
item_info_df_muestra = item_info_df.sample(n=15000, random_state=semilla).reset_index(drop=True)

In [10]:
item_info_df_muestra.to_csv('recsys-pf/item_info_resumen.csv')

In [11]:
# LLM (QWEN)
print("Cargando el modelo Qwen2.5-1.5B")
generador_qwen = pipeline(
    "text-generation",
    model="Qwen/Qwen2.5-1.5B-Instruct",
    model_kwargs={"torch_dtype": torch.bfloat16},
    device_map="auto",
)

# Definimos los Prompts del Sistema que corregimos
PROMPT_SUMMARIZER = (
    "You are an expert data annotator for computer vision. Your task is to read a noisy "
    "social media post and translate it into a concise, less than 20-word declarative "
    "description of the visual scene it implies.\n"
    "Instructions:\n"
    "- Limit the description to strictly less than 20 words.\n"
    "- Concentrate on capturing visually observable attributes (subjects, setting, clothing, objects). "
    "If they are not explicit, logically infer them from the provided text, emojis, and hashtags.\n"
    "- Refrain from using engaging, subjective, or persuasive language. Use strictly declarative and objective language."
)

PROMPT_EVALUATOR = (
    "You are a summary evaluator for data annotation in computer vision. Your task is to evaluate a "
    "social media post summary according to the following criteria:\n"
    "- The summary must be strictly less than 20 words.\n"
    "- It must encapsulate the visual elements explicitly present in the original description, or "
    "correctly infer visual elements that would logically appear in an accompanying image.\n"
    "- It must use strictly declarative and objective language.\n"
    "- You must provide feedback and revision suggestions focused solely on the presence or absence of visual elements.\n"
    "Instructions:\n"
    "- If you find the summary is too long, ask for a shorter summary.\n"
    "- If you determine that no further revisions are needed and all criteria are met, end your output "
    "with <STOP> (without any extra text)."
)

PROMPT_REFINER = (
    "You are an expert data annotator for computer vision. Your task is to refine a summary based on "
    "the provided feedback. Follow all the suggestions exactly and do not provide any additional commentary. "
    "Give only one final summary as your output.\n"
    "Instructions:\n"
    "- Limit the summary to strictly fewer than 20 words.\n"
    "- Include in your description only elements which are visually observable or logically inferable from the original description.\n"
    "- Use strictly declarative and objective language."
)

def consultar_llm(prompt_sistema, prompt_usuario, max_tokens):
    mensajes = [
        {"role": "system", "content": prompt_sistema},
        {"role": "user", "content": prompt_usuario}
    ]
    salida = generador_qwen(
        mensajes,
        max_new_tokens=max_tokens,
        temperature=0.3,
        do_sample=True
    )
    return salida[0]["generated_text"][-1]["content"].strip()

Cargando el modelo Qwen2.5-1.5B

config.json:   0%|          | 0.00/660 [00:00<?, ?B/s]

`torch_dtype` is deprecated! Use `dtype` instead!
`torch_dtype` is deprecated! Use `dtype` instead!

model.safetensors:   0%|          | 0.00/3.09G [00:00<?, ?B/s]

Loading weights:   0%|          | 0/338 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/242 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/7.30k [00:00<?, ?B/s]

vocab.json:   0%|          | 0.00/2.78M [00:00<?, ?B/s]

merges.txt:   0%|          | 0.00/1.67M [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/7.03M [00:00<?, ?B/s]

In [ ]:
def vl_clip():
    rutas = sorted(glob.glob("recsys-pf/resized_images/*.jpg"))
    max_iteraciones = 5 # para el llm

    # Para guardar features
    carpeta_salida = "Features"
    os.makedirs(carpeta_salida, exist_ok=True) # Crea la carpeta si no existe, no falla si ya está
    frecuencia_guardado = 1000 # Cuántas imágenes guardar por lote
    numero_lote = 0 # Contador para nombrar los archivos

    ruta_img_features = os.path.join(carpeta_salida, "images_features.pt")
    ruta_txt_features = os.path.join(carpeta_salida, "textual_features.pt")


    images_features = {}
    textual_features = {}
    for idx, ruta in enumerate(rutas):
        item_id = os.path.basename(ruta).replace(".jpg", "")
        image = Image.open(ruta).convert("RGB")
        # Sacar tag asociada a imagen para buscarla con dion
        item_info = item_info_df[ item_info_df["item_id"] == item_id ]
        tags = item_info["tag"].iloc[0].split("·")
        text_labels = ". ".join(tags) + "."
        # Quizá esto no sea tan sencillo, estas categorías pueden ser más abstractas que "vestido" o "mochila". Cosas como "comedia"

        inputs = dino_processor(images=image, text=text_labels, return_tensors="pt").to(device)
        with torch.no_grad():
            outputs = dino(**inputs)

        result_boxes = dino_processor.post_process_grounded_object_detection(
            outputs,
            inputs.input_ids,
            threshold=0.4,
            text_threshold=0.3,
            target_sizes=[image.size[::-1]]
        )

        # print("\nImagen: ", item_id)
        # print("Categoría buscada: ", text_labels[0])
        result_box = result_boxes[0]

        # Recortar imagen a caja encontrada si se puede
        score, box = result_box["scores"], result_box["boxes"]
        if score.numel() != 0:
            x_min, y_min, x_max, y_max = [int(coord) for coord in box[0].cpu().tolist()]
            image = image.crop((x_min, y_min, x_max, y_max))
        else:
            # print("no se encontro objeto")
            pass

        # obtener features de la imagen con CLIP
        inputs = clip_processor(images=image, return_tensors="pt")
        with torch.no_grad():
            image_features = clip.get_image_features(**inputs)
        image_features = image_features / image_features.norm(p=2, dim=-1, keepdim=True)
        images_features[item_id] = image_features.cpu()

        # Creación query con LLM
        textos = tags + [item_info["title"].iloc[0]] + [item_info["description"].iloc[0]]
        texto = " ".join( x for x in textos if isinstance(x, str) )
        prompt_usu_sum = f"Original post: {texto}"
        resumen_actual = consultar_llm(PROMPT_SUMMARIZER, prompt_usu_sum, max_tokens=25)

        for i in range(max_iteraciones):
            prompt_usu_eval = f"Original post: {texto}\nCurrent summary: {resumen_actual}"
            feedback = consultar_llm(PROMPT_EVALUATOR, prompt_usu_eval, max_tokens=50)
            if "<STOP>" in feedback:
                    break

            prompt_usu_ref = (
                f"Original post: {texto}\n"
                f"Current summary: {resumen_actual}\n"
                f"Evaluator Feedback: {feedback}"
            )
            resumen_actual = consultar_llm(PROMPT_REFINER, prompt_usu_ref, max_tokens=25)

        # print(texto)
        # print(resumen_actual, "\n")

        # Obtener features de texto en base a características con CLIP
        inputs = clip_processor( text=resumen_actual, return_tensors="pt", padding=True, truncation=True )
        with torch.no_grad():
            text_features = clip.get_text_features(**inputs)
        text_features = text_features / text_features.norm(p=2, dim=-1, keepdim=True)
        textual_features[item_id] = text_features.cpu()

        if (idx + 1) % frecuencia_guardado == 0:
            print(f"\n[Guardando Lote {numero_lote}] Progreso: {idx + 1} / {len(rutas)} imágenes...")

            ruta_img_features = os.path.join(carpeta_salida, f"images_batch_{numero_lote}.pt")
            ruta_txt_features = os.path.join(carpeta_salida, f"text_batch_{numero_lote}.pt")

            torch.save(images_features, ruta_img_features)
            torch.save(textual_features, ruta_txt_features)

            # ¡VACIAR LA MEMORIA RAM!
            images_features.clear()
            textual_features.clear()
            numero_lote += 1

    if len(images_features) > 0:
        ruta_img_features = os.path.join(carpeta_salida, f"images_batch_{numero_lote}.pt")
        ruta_txt_features = os.path.join(carpeta_salida, f"text_batch_{numero_lote}.pt")
        torch.save(images_features, ruta_img_features)
        torch.save(textual_features, ruta_txt_features)
        print(f"\n[Guardando Lote Final {numero_lote}]")

generar las queries de texto por separado

In [ ]:

# --- CELDA DE PRE-CÁLCULO DEL LLM ---
from tqdm.auto import tqdm
import transformers
transformers.logging.set_verbosity_error()

item_info_df = item_info_df_muestra.loc[500 : 5000]


if 'final_summary' not in item_info_df.columns:
    item_info_df['final_summary'] = None

max_iteraciones_llm = 2
frecuencia_guardado = 250
ruta_csv_actualizado = 'recsys-pf/item_info_resumen_queries1.csv'


print(f"Iniciando ciclo LLM para {len(item_info_df)} items...")

for idx, row in tqdm(item_info_df.iterrows(), total=len(item_info_df)):
    # Si esta fila ya tiene un resumen final, la saltamos
    if pd.notna(row['final_summary']):
        continue

    item_id = row['item_id']

    # Extraer y limpiar textos originales
    tags = str(row['tag']).split("·") if pd.notna(row['tag']) else []
    titulo = str(row['title']) if pd.notna(row['title']) else ""
    desc = str(row['description']) if pd.notna(row['description']) else ""

    textos = tags + [titulo] + [desc]
    texto_completo = " ".join(x for x in textos if isinstance(x, str) and x.strip() != "")

    # Ciclo del LLM
    prompt_usu_sum = f"Original post: {texto_completo}"
    resumen_actual = consultar_llm(PROMPT_SUMMARIZER, prompt_usu_sum, max_tokens=25)

    for i in range(max_iteraciones_llm):
        prompt_usu_eval = f"Original post: {texto_completo}\nCurrent summary: {resumen_actual}"
        feedback = consultar_llm(PROMPT_EVALUATOR, prompt_usu_eval, max_tokens=50)

        if "<STOP>" in feedback:
            break

        prompt_usu_ref = (
            f"Original post: {texto_completo}\n"
            f"Current summary: {resumen_actual}\n"
            f"Evaluator Feedback: {feedback}"
        )
        resumen_actual = consultar_llm(PROMPT_REFINER, prompt_usu_ref, max_tokens=25)

    item_info_df.at[idx, 'final_summary'] = resumen_actual

    if (idx + 1) % frecuencia_guardado == 0:
        print(f"[Checkpoint LLM] Textos procesados: {idx + 1} / {len(item_info_df)}")
        item_info_df.to_csv(ruta_csv_actualizado, index=False)

# Guardado final una vez termina el bucle
item_info_df.to_csv(ruta_csv_actualizado, index=False)
print("¡Pre-cálculo de textos finalizado con éxito!")

Iniciando ciclo LLM para 5001 items...

/tmp/ipykernel_7416/1319071470.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  item_info_df['final_summary'] = None

  0%|          | 0/5001 [00:00<?, ?it/s]

[Checkpoint LLM] Textos procesados: 250 / 5001
[Checkpoint LLM] Textos procesados: 500 / 5001
[Checkpoint LLM] Textos procesados: 750 / 5001

In [ ]:
item_info_df

,item_id,view_number,comment_number,thumbup_number,share_number,coin_number,favorite_number,barrage_number,title,tag,description,final_summary
0,i192714,799668.0,739.0,8050.0,220.0,84.0,1049.0,510.0,"My boyfriend gave me a turtle, and it suddenly...",Pet Reptiles,Should I brush it off?,"Pet turtle growing hair, needs attention."
1,i225967,1201395.0,102.0,20424.0,738.0,502.0,4307.0,510.0,Who's not a baby anymore! Alaska is being bull...,Dogs,BGM: Don't Leave Me (Ne Me Quitte Pas) - Regin...,"Alaska, no longer a puppy, battles bullies out..."
2,i8061,2633706.0,2502.0,160379.0,11161.0,2439.0,32801.0,1696.0,New York subway rules that pets can't ride the...,Dogs,wb,Dogs must be in a bag on NYC subways; no pet r...
3,i217203,922049.0,244.0,9878.0,344.0,228.0,2129.0,1374.0,The biggest dog in the world. It's so ugly and...,Dogs,"Super love big dogs, the family has a baby Lab...",A massive bulldog with an eye-opening reaction...
4,i349133,186671.0,50.0,1630.0,67.0,87.0,1617.0,76.0,Taylor Swift: Selena and Mould perform Hands T...,Live Music,NaN,"Taylor Swift performs ""Hands To Myself"" with S..."
...,...,...,...,...,...,...,...,...,...,...,...,...
82860,i71755,917316.0,565.0,15861.0,1602.0,4006.0,5999.0,579.0,😈ғᴀʟʟᴇɴ ᴀɴɢᴇʟ😈,Esports,The most important thing to remember is that i...,None
82861,i54680,1700845.0,1779.0,137865.0,6798.0,17289.0,28887.0,2239.0,👴 👋 🦊,Short Film·Hand-drawn·Dubbing,Master Strokes Fox's Tail》Planner/Copywriter：E...,None
82862,i65674,119400.0,192.0,8469.0,313.0,1019.0,3845.0,108.0,𝑻𝒓𝒊𝒔𝒉 𝑼𝒏𝒂,MAD·AMV,BGM: Gaminl - POP／STARS,None
82863,i128412,562279.0,1185.0,48396.0,1375.0,10905.0,26126.0,218.0,𝓓𝓻𝓸𝔀𝓷 𝓲𝓷 𝓵𝓸𝓿𝓮 𝔀𝓲𝓽𝓱 𝔂𝓸𝓾,MAD·AMV,hold your hand and grow old with your son,None
82864,i17380,349856.0,853.0,41093.0,1764.0,20772.0,24492.0,937.0,𝕯𝖗𝖊𝖆𝖒,MAD·AMV,"Happy New Year, two weeks ago on the good draf...",None

In [ ]:
vl_clip()

In [ ]:
# Faltaría el codigo que hace la recomendación+
item_info_df

,item_id,view_number,comment_number,thumbup_number,share_number,coin_number,favorite_number,barrage_number,title,tag,description
0,i192714,799668.0,739.0,8050.0,220.0,84.0,1049.0,510.0,"My boyfriend gave me a turtle, and it suddenly...",Pet Reptiles,Should I brush it off?
1,i225967,1201395.0,102.0,20424.0,738.0,502.0,4307.0,510.0,Who's not a baby anymore! Alaska is being bull...,Dogs,BGM: Don't Leave Me (Ne Me Quitte Pas) - Regin...
2,i8061,2633706.0,2502.0,160379.0,11161.0,2439.0,32801.0,1696.0,New York subway rules that pets can't ride the...,Dogs,wb
3,i217203,922049.0,244.0,9878.0,344.0,228.0,2129.0,1374.0,The biggest dog in the world. It's so ugly and...,Dogs,"Super love big dogs, the family has a baby Lab..."
4,i349133,186671.0,50.0,1630.0,67.0,87.0,1617.0,76.0,Taylor Swift: Selena and Mould perform Hands T...,Live Music,NaN
...,...,...,...,...,...,...,...,...,...,...,...
82860,i71755,917316.0,565.0,15861.0,1602.0,4006.0,5999.0,579.0,😈ғᴀʟʟᴇɴ ᴀɴɢᴇʟ😈,Esports,The most important thing to remember is that i...
82861,i54680,1700845.0,1779.0,137865.0,6798.0,17289.0,28887.0,2239.0,👴 👋 🦊,Short Film·Hand-drawn·Dubbing,Master Strokes Fox's Tail》Planner/Copywriter：E...
82862,i65674,119400.0,192.0,8469.0,313.0,1019.0,3845.0,108.0,𝑻𝒓𝒊𝒔𝒉 𝑼𝒏𝒂,MAD·AMV,BGM: Gaminl - POP／STARS
82863,i128412,562279.0,1185.0,48396.0,1375.0,10905.0,26126.0,218.0,𝓓𝓻𝓸𝔀𝓷 𝓲𝓷 𝓵𝓸𝓿𝓮 𝔀𝓲𝓽𝓱 𝔂𝓸𝓾,MAD·AMV,hold your hand and grow old with your son
82864,i17380,349856.0,853.0,41093.0,1764.0,20772.0,24492.0,937.0,𝕯𝖗𝖊𝖆𝖒,MAD·AMV,"Happy New Year, two weeks ago on the good draf..."

In [ ]:
# De Gemini, la idea es hacer recomendación en base a "queries" de texto, encontrar la imagen más parecida usando similitud coseno
import random

def evaluar_retrieval(ruta_img_features, ruta_txt_features, num_test_samples=100):
    images_dict = torch.load(ruta_img_features)
    text_dict = torch.load(ruta_txt_features)

    item_ids = list(images_dict.keys())

    # Apilamos los tensores individuales en un solo tensor gigante (N, 512)
    # Usamos .squeeze() por si el tensor quedó con forma (1, 512)
    gallery_images = torch.stack([images_dict[i].squeeze() for i in item_ids])
    all_texts = torch.stack([text_dict[i].squeeze() for i in item_ids])

    # 2. Separación del Test Set (Seleccionamos 1,000 queries al azar)
    # random.seed(42) # Para reproducibilidad
    test_ids = random.sample(item_ids, min(num_test_samples, len(item_ids)))

    # Guardamos los índices numéricos de las imágenes correctas (Ground Truth)
    test_indices = [item_ids.index(item_id) for item_id in test_ids]

    # Extraemos solo los vectores de texto de nuestro Test Set
    query_texts = all_texts[test_indices]

    print(f"Galería de imágenes: {gallery_images.shape}")
    print(f"Queries de prueba: {query_texts.shape}")

    # 3. Calcular la Similitud Coseno
    # Como los vectores ya están normalizados (L2), la similitud coseno
    # es simplemente una multiplicación de matrices (Producto Punto)
    print("Calculando similitudes...")
    similitudes = torch.matmul(query_texts, gallery_images.T) # Forma: (1000, N)

    # 4. Calcular Métricas: HITS@5 y MRR
    hits_5 = 0
    mrr_suma = 0.0

    print("Evaluando resultados...")
    for i, correct_idx in enumerate(test_indices):
        # Obtenemos las similitudes para la query 'i'
        sims_query = similitudes[i]

        # Ordenamos de mayor a menor y sacamos los índices
        # Usamos topk para no ordenar todo si el catálogo es gigante, con el top 100 basta para estas métricas
        _, top_indices = sims_query.topk(100)
        top_indices = top_indices.tolist()

        # Buscamos en qué posición (rango) quedó la imagen correcta
        if correct_idx in top_indices:
            # .index() devuelve 0 para la primera posición, así que sumamos 1
            rank = top_indices.index(correct_idx) + 1

            # HITS@5: ¿Quedó en el top 5?
            if rank <= 5:
                hits_5 += 1

            # MRR: Inverso del rango
            mrr_suma += (1.0 / rank)

    # Calcular promedios finales
    total_queries = len(test_ids)
    final_hits_5 = hits_5 / total_queries
    final_mrr = mrr_suma / total_queries

    print("\n--- RESULTADOS DE RECUPERACIÓN (ZERO-SHOT) ---")
    print(f"HITS@5 : {final_hits_5:.4f} (El {final_hits_5*100:.1f}% de las veces la imagen correcta estuvo en el Top 5)")
    print(f"MRR    : {final_mrr:.4f}")

    return final_hits_5, final_mrr

# Para ejecutarlo:
# evaluar_retrieval("Features/images_features.pt", "Features/textual_features.pt", num_test_samples=100)